=== mikhnyukv/JWD/target/test-classes/papersSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:task3.namespace"
           xmlns="urn:task3.namespace">
<xs:element name="Papers">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="Paper" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Title" type="xs:string"/>
                        <xs:element name="Volume" type="xs:integer"/>
                        <xs:element name="Glossy" type="xs:boolean"/>
                        <xs:element name="SubscriptionIndex" type="xs:boolean"/>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:integer" use="required"/>
                    <xs:attribute name="type" type="xs:string" use="required"/>
                    <xs:attribute name="monthly" type="xs:boolean" use="optional" default="true"/>
                    <xs:attribute name="color" type="xs:boolean" use="optional" default="true"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== mikhnyukv/JWD/target/test-classes/papers.xml
<?xml version="1.0"?>
<Papers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="urn:task3.namespace"
        xsi:schemaLocation="papersSchema.xsd">
    <Paper id="1" type="magazine" monthly="true" color="true">
        <Title>Vogue</Title>
        <Volume>35</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
    <Paper id="2" type="newspaper" monthly="true" color="true">
        <Title>Forbs</Title>
        <Volume>45</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
    <Paper id="3" type="booklet" monthly="true" color="true">
        <Title>CarDrift</Title>
        <Volume>75</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
    <Paper id="4" type="newspaper" monthly="true" color="true">
        <Title>Garden</Title>
        <Volume>200</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
    <Paper id="5" type="newspaper" monthly="true" color="true">
        <Title>Village</Title>
        <Volume>20</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
    <Paper id="6" type="newspaper" monthly="true" color="true">
        <Title>Garden</Title>
        <Volume>200</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
    <Paper id="7" type="newspaper" monthly="true" color="true">
        <Title>YourCity</Title>
        <Volume>200</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
    <Paper id="8" type="newspaper" monthly="true" color="true">
        <Title>Garden</Title>
        <Volume>200</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
    <Paper id="9" type="newspaper" monthly="true" color="true">
        <Title>Garden</Title>
        <Volume>200</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
    <Paper id="10" type="newspaper" monthly="true" color="true">
        <Title>Garden</Title>
        <Volume>200</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
    <Paper id="11" type="newspaper" monthly="true" color="true">
        <Title>Garden</Title>
        <Volume>200</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
    <Paper id="12" type="newspaper" monthly="true" color="true">
        <Title>Garden</Title>
        <Volume>200</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
    <Paper id="13" type="newspaper" monthly="true" color="true">
        <Title>Garden</Title>
        <Volume>200</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
    <Paper id="14" type="newspaper" monthly="true" color="true">
        <Title>Garden</Title>
        <Volume>200</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
    <Paper id="15" type="newspaper" monthly="true" color="true">
        <Title>Garden</Title>
        <Volume>200</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
    <Paper id="16" type="newspaper" monthly="true" color="true">
        <Title>Garden</Title>
        <Volume>200</Volume>
        <Glossy>true</Glossy>
        <SubscriptionIndex>true</SubscriptionIndex>
    </Paper>
</Papers>
